version: '3.9'
services:
  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-seed:
    image: mongo:4.4.6
    links:
      - mongo
    volumes:
      - ./src/seed/admin.json:/admin.json
    command: "mongoimport --uri mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/${DB_NAME}?authSource=admin --collection users --drop --file /admin.json"

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}

  dave:
    image: dave
    build: .
    restart: always
    ports:
      - 4000:${PORT}
    volumes:
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - .:/usr/app
    command: "wait-for-it.sh --strict mongo:27017 -- npm run dev"
    depends_on:
      - mongo
