apiVersion: apps/v1
kind: Deployment
metadata:
  name: dave-deployment
  labels:
    app: dave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dave
  template:
    metadata:
      labels:
        app: dave
    spec:
      containers:
      - name: dave
        image: daivasmara/dave:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: secret
              key: SECRET_KEY
        - name: SECRET_REFRESH_KEY
          valueFrom: 
            secretKeyRef:
              name: secret
              key: SECRET_REFRESH_KEY
        - name: DB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongo-configmap
              key: DATABASE_URL
        - name: DB_NAME
          valueFrom: 
            secretKeyRef:
              name: secret
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom: 
            secretKeyRef:
              name: secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: dave-service
spec:
  selector:
    app: dave
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
